openapi: 3.1.0
info:
  title: MyKayak API
  version: 1.0.0
  description: Enhanced FICr API
servers:
  - url: https://api.mykayak.fuffo.net
    description: Production server
paths:
  /athletes:
    get:
      summary: Get list of athletes
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
  /athlete/{id}:
    get:
      summary: Get athlete by ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        distance:
                          type: integer # in meters
                        time:
                          type: integer # in milliseconds
                        raceId:
                          type: string
                  races:
                    type: array
                    items:
                      type: string
                      
      parameters:
        - name: raceLimit
          in: query
          required: false
          schema:
            type: integer
            default: 0
  /race/{id}:
    get:
      summary: Get race by ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  dateTime:
                    type: string
                    format: date-time
                  distance:
                    type: integer # in meters
                  raceId:
                    type: string
                    format: uuid
                  lane:
                    type: integer
                  placement: 
                    type: integer
                  time:
                    type: integer
                  delta:
                    type: integer